### ISSUE TITLE
Add useful pages / sections

### ISSUE THREAD

**Issue by mslw** [distribits/distribits-2024-website#1]
These came up in previous discussions, with the must-have in bold.

- [x] **about** (meeting overview)
- [x] **registration** / submission / call for contributions
- [x] **location**
- [x] **schedule**
- [x] code of conduct
- [ ] FAQ
- [x] newsfeed (a.k.a. blog posts)
- [ ] sponsors (if we have any)

**Comment by jsheunis** [comment]
We made a note somewhere of the tool we intend to use for rendering the schedule, can someone recall what it is?

**Comment by adswa** [comment]
Yes Giggity

**Comment by adswa** [comment]
There are a large amount of very affordable accomodations within a 1-2km range of the location (those are google search results for a single night stay for one person at a random date):

![image](https://github.com/datalad/distribits-2024-website/assets/29738718/cbcc2d3d-159c-4256-87d6-620289dc98b4)

One that seems in particular recommendable might be https://blkhostel.de (not a hotel, but a hostel, so particularly affordable and with possibilities to share rooms with several people - its reviews and photos look fantastic, and for a date this september a room for 3 adults costs ~70€ per night). It is also the closest accommodation to the venue.

Another accommodation very close by is https://www.altstadthotelbarcelona.de. Its a small-ish bed-and-breakfast, family-owned, with only 17 rooms (starting at 55€ for a single room, and room capacity for up to 3 adults). In such small hotels we could even call and ask whether they'd be willing to reserve a room contingent for us. Added advantage is that is had an irish pub.

**Comment by jsheunis** [comment]
Closing this issue since it does not anything more in particular that needs to be addressed.

FAQ ans Support pages can be added to the website if and when they become applicable. 

Accommodation suggestions (e.g. https://github.com/distribits/distribits-2024-website/issues/1#issuecomment-1711468440) could or could not be added to the Location page of the website.
